# Generated by Django 4.1 on 2022-08-18 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MO', 'Mortgage'), ('PE', 'Personal'), ('PL', 'Pledge')], max_length=2)),
                ('date', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'PRESTAMOS',
            },
        ),
    ]
