# Generated by Django 4.1 on 2022-08-19 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cancelled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
