# Generated by Django 4.1 on 2022-08-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='type',
            field=models.CharField(choices=[('MO', 'Mortgage'), ('PE', 'Personal'), ('PL', 'Pledge'), ('ST', 'Student'), ('VE', 'Vehicle')], max_length=2),
        ),
    ]
