# Generated by Django 4.1 on 2022-08-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamo_cancelled_alter_prestamo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
