# Generated by Django 4.1 on 2022-08-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_address_alter_branch_address_alter_employee_address'),
        ('cliente', '0002_rename_branch_id_cliente_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.address'),
        ),
    ]
