# Generated by Django 4.1 on 2022-08-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
