# Generated by Django 4.1 on 2022-08-18 23:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CA', 'Current Account'), ('SA', 'Savings Account'), ('SAU', 'Savings Account (USD)')], default='CA', max_length=3)),
                ('iban', models.CharField(editable=False, max_length=200, unique=True)),
                ('balance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'CUENTAS',
            },
        ),
    ]
