# Generated by Django 4.1 on 2022-08-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_cuenta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='iban',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
