# Generated by Django 4.1 on 2022-08-22 18:39

import cuentas.accounts_util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='alias',
            field=models.CharField(default=cuentas.accounts_util.generate_alias, max_length=200, unique=True),
        ),
    ]
