# Generated by Django 4.1 on 2022-08-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_cuenta_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date']},
        ),
    ]
