# Generated by Django 4.1 on 2022-08-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_cuenta_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.UUIDField(default=280072758978231817802995901605519390805, primary_key=True, serialize=False),
        ),
    ]
