# Generated by Django 4.1 on 2022-08-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
    ]
