# Generated by Django 4.1 on 2022-08-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_cuenta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default='286624958506878983084742689602634480415', max_length=10, primary_key=True, serialize=False),
        ),
    ]
