# Generated by Django 4.1 on 2022-08-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_alter_cuenta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='iban',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default='2882833464', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
