# Generated by Django 4.1 on 2022-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_cuenta_iban_alter_cuenta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='costumer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default='2632740690', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
