# Generated by Django 4.1 on 2022-08-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_rename_costumer_cuenta_customer_alter_cuenta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default='1024728266', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
