# Generated by Django 4.1 on 2022-08-19 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0009_alter_cuenta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default='9162661311', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
