# Generated by Django 4.1 on 2022-08-19 21:59

import cuentas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_alter_cuenta_customer_alter_cuenta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default=cuentas.models.account_id_generator, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
