# Generated by Django 4.1 on 2022-08-20 21:15

from django.db import migrations, models
import tarjetas.card_utils


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='number',
            field=models.CharField(default=tarjetas.card_utils.generate_card_number, max_length=16),
        ),
    ]
