# Generated by Django 4.1 on 2022-08-20 22:04

from django.db import migrations, models
import tarjetas.card_utils


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_alter_tarjeta_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='cvv',
            field=models.CharField(default=tarjetas.card_utils.generate_cvv, max_length=4),
        ),
    ]
